//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 10:00:56 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jozi.com/spring-ws-insurance", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.jozi.spring_ws_insurance;
